kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
  template:
    metadata:
      labels:
        app: java-springboot-app
    spec:
      containers:
        - name: my-java-springboot
          image: java-springboot-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          volumeMounts:
          - name: certpath
            mountPath: /opt/ssl
          env:
          - name: AZURE_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: example 
                key: AZURE_CLIENT_ID
          - name: AZURE_TENANT_ID
            valueFrom:
              configMapKeyRef:
                name: example 
                key: AZURE_TENANT_ID
          - name: AZURE_CLIENT_CERTIFICATE_PATH
            value: /opt/ssl/spncert
      volumes:
      - name: certpath
        configMap:
          name: example
          key: AZURE_CLIENT_CERTIFICATE_PATH
          items:
          - key: AZURE_CLIENT_CERTIFICATE_PATH
            path: spncert
---
kind: Service
apiVersion: v1
metadata:
  name: my-java-springboot-svc
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: java-springboot-app